# Generated by Django 6.0 on 2026-03-26 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='DailyVoteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VoterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_hash', 'last_seen'], name='PlayWW_vote_ip_hash_16f076_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='PlayWW.champion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='PlayWW.votersession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'vote_order'], name='PlayWW_vote_session_4fbb00_idx')],
                'unique_together': {('session', 'champion'), ('session', 'vote_order')},
            },
        ),
    ]
